services:
  db:
    image: postgres:17-alpine
    restart: no
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    env_file:
      - ./.env
    ports:
      - 5432:5432
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
